databases:
  - name: task_manager
    databaseName: task_manager
    user: task_manager
    region: frankfurt
    plan: free
    postgresMajorVersion: 13
    ipAllowList: []

services:
  - type: web
    name: task_manager
    region: frankfurt
    plan: free
    env: docker
    repo: https://github.com/mikekurkin/TaskManager.git
    branch: develop
    dockerCommand: ./render-demo-entrypoint.sh
    envVars:
      - key: PORT
        value: 3000
      - key: DEMO
        value: true
      - key: REPLANT_SEED
        value: ''
      - key: RAILS_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: task_manager
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
